### ISSUE TITLE
Mupen Utilities Exception

### ISSUE THREAD

**Issue by LukeSaward1** [Aurumaker72/MupenUtilities#5]
### MupenUtilities crash log

[exception.log](https://github.com/Aurumaker72/MupenUtilities/files/6719798/exception.log)

**Comment by Aurumaker72** [comment]
I'll look into this asap

**Comment by Aurumaker72** [comment]
Issue resolved in commit 2f2d4cc0223ebaff2a0bfe0226e91d47a24f9fcb
The cause was a race condition between TAS Studio and M64 Loading thread
