### ISSUE TITLE
Exception when trying to pasting copied frame(s)

### ISSUE THREAD

**Issue by mekb-turtle** [Aurumaker72/MupenUtilities#6]
I've two MU open in seperate directories, both open to seperate movies and move mode off, "a" is read-only, "b" isn't. I select a bunch of frames on "a" with holding shift and ctrl+C to copy, on "b" I select my frame and hit ctrl+V and "b" crashes with [exception.log](https://github.com/Aurumaker72/MupenUtilities/files/7403873/exception.log)

**Comment by Aurumaker72** [comment]
Multiple instances cant interoperate with same data. Pasting currently is broken overall so I need to redo that.

**Comment by mekb-turtle** [comment]
ah okay, thanks anyways

**Comment by Aurumaker72** [comment]
im reimplementing pasting

**Comment by Aurumaker72** [comment]
This has been implemented correctly and cleanly in my continuation of MupenUtilities, [MupenToolkit](https://www.github.com/Aurumaker72/MupenToolkit).
